[versions]
# GeckoLib
    geckolib = "4.5.4.2"

# General Dependencies
    minecraft-range = "[1.20.6,)"
    minecraft = "1.20.6"
    parchment-minecraft = "1.20.6"
    parchment = "2024.06.02"

# Fabric Settings
    fabric = "0.15.11"
    fabric-api = "0.100.0+1.20.6"

# Forge Settings
    forge-fml-range = "[50,)"
    forge-range = "[50.1.0,)"
    forge = "50.1.3"
    forge-mc = "1.20.6-50.1.3"
    jopt-simple = "5.0.4"

# Neoforge Settings
    neoforge-loader-range = "[2,)"
    neoforge-range = "[20.6.115,)"
    neoforge = "20.6.115"

# Dependencies
    mixin = "0.8.6"
    mixinextras = "0.3.5"
    mixinextras-range = "[0.3.5,)"
    examplemod = "1.0.0"

# Plugins
    plugin-minotaur = "2.8.7"
    plugin-curseforge-gradle = "1.1.24"
    plugin-idea-ext = "1.1.8"
    plugin-forge-gradle = "[6.0,6.2)"
    plugin-mixin = "0.7.+"
    plugin-parchment-forge-gradle = "1.+"
    plugin-neoforge-gradle = "7.0.142"
    plugin-loom = "1.6-SNAPSHOT"
    plugin-vanilla-gradle = "0.2.1-SNAPSHOT"

[libraries]
# Mixin
    mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
    mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }
    mixinextras-forge = { group = "io.github.llamalad7", name = "mixinextras-forge", version.ref = "mixinextras" }

# Platform
    neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
    forge = { group = "net.minecraftforge", name = "forge", version.ref = "forge-mc" }
    fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
    fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
    minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# Testing
    examplemod-common = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-common-1.20.6", version.ref = "examplemod" }
    examplemod-fabric = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-fabric-1.20.6", version.ref = "examplemod" }
    examplemod-forge = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-forge-1.20.6", version.ref = "examplemod" }
    examplemod-neoforge = { group = "software.bernie.geckolib", name = "geckolib-examples-ml-neoforge-1.20.6", version.ref = "examplemod" }

# Other
    jopt-simple = { group = "net.sf.jopt-simple", name = "jopt-simple", version.ref = "jopt-simple" } # Forge's temporary hacky solution

[plugins]
# Publishing
    minotaur = { id = "com.modrinth.minotaur", version.ref = "plugin-minotaur" }
    curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "plugin-curseforge-gradle" }

# Platform
    vanillagradle = { id = "org.spongepowered.gradle.vanilla", version.ref = "plugin-vanilla-gradle" }
    neogradle = { id = "net.neoforged.gradle.userdev", version.ref = "plugin-neoforge-gradle" }
    forgegradle = { id = "net.minecraftforge.gradle", version.ref = "plugin-forge-gradle" }
    loom = { id = "fabric-loom", version.ref = "plugin-loom" }
    parchmentforgegradle = { id = "org.parchmentmc.librarian.forgegradle", version.ref = "plugin-parchment-forge-gradle" }

# Misc
    ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "plugin-idea-ext" }
    mixin = { id = "org.spongepowered.mixin", version.ref = "plugin-mixin" }